apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  template:
    spec:
      containers:
      - name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: root-password
